[versions]
dokka = "2.1.0"
git-versioning = "6.4.4"
kotlin = "2.2.21"
kotlinx-bcv = "0.18.1"
kotlinx-html = "0.12.0"
kotlinx-serialization = "1.9.0"
ktor = "3.3.2"
maven-publish = "0.34.0"
simplejavamail = "8.12.6"

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
git-versioning = { id = "me.qoomon.git-versioning", version.ref = "git-versioning" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-bcv = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinx-bcv" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

[libraries]
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "kotlinx-html" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
simplejavamail = { module = "org.simplejavamail:simple-java-mail", version.ref = "simplejavamail" }
